### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by psabharwal123** [aws-lite/aws-lite#165]
### Describe the issue

most pages like https://aws-lite.org/services/dynamodb give an error

### Expected behavior

https://aws-lite.org/services/dynamodb should work

### Steps to reproduce

go to https://aws-lite.org/services/dynamodb

### Platform / version

- OS + version: (e.g. iOS 17.2)
- Node version: (e.g. Node.js 20.5)
- Package manager version: (e.g. npm 10.2)
- Browser: (e.g. Chrome 70.5, if applicable)

### How urgent do you feel this bug is?

None

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by tbeseda** [comment]
Thanks for the heads up! There is definitely an issue. I'm fairly certain it's upstream from this site, so I will work to fix it there tomorrow.
Until then you can view docs for each service in this repo. For example the DynamoDB docs are in the README here https://github.com/aws-lite/aws-lite/tree/main/plugins/dynamodb

**Comment by ryanblock** [comment]
Thanks for taking a look at this, @tbeseda!

**Comment by tbeseda** [comment]
Website is back online https://aws-lite.org/services/dynamodb
Thanks again for reporting

**Comment by psabharwal123** [comment]
thanks!
