### ISSUE TITLE
Request function override

### ISSUE THREAD

**Issue by fl0wo** [aws-lite/aws-lite#171]
### Describe the problem underlying the enhancement request

I'm trying to run aws-lite/sqs on a Cloudflare worker, but https.request module is not yet implemented in their node environment (the Workers run on).

Therefore when I try to run aws-lite to push a message on SQS I get 'Error https.request is not implemented yet'.

https://discord.com/channels/595317990191398933/1293327443746230282

### Describe the solution you'd like (if any)

I think would be enough to specify a custom request/fetch function to use for sending https messages:

```
    const aws = await awsLite({
        plugins: [ import("@aws-lite/sqs") ],
        accessKeyId: 'my-key',
        secretAccessKey: 'my-sec',
        region: 'eu-central-1',
        
        fetch: async (args) => myCustomFetch(args)
    });
```
   

### Describe alternative solutions you've considered

Idealy, Cloudflare could just implement https.request support on Workers, and this would not be a necessity.

### Additional context or notes

Why I'm even pushing to AWS SQS from Cloudflare?

I'm using Cloudflare for some edge things, and AWS for heavier computations, therefore I need to move from CF to SQS at some point, invoking SQS.

And I do not want to wrap SQS with ApiGtw + Lambda, instead want to invoke it directly using aws-lite because it's an amazing library.

**Comment by ryanblock** [comment]
Thank you! Sorry this didn't work for you. Unfortunately there is a lot of underlying logic in aws-lite related to things like rate limiting, retries, pagination, etc that does not lend itself to dropping in a different HTTP request method.

Ideally CF Workers would improve their Node.js support, which everyone can benefit from.
